### PR TITLE
Xyzc override rebased

### PR DESCRIPTION
**Pull request by maierl**
same as #13 but mergeable.

> ilastik gave me a XYT .tiff instead of a XYZC .tiff, so I implemented an override within knime.
> 
> missing input cells should be handled correctly by readResultImages().

### CODE REVIEW

**Comment by dietzc** [comment]
do we need the two "merge" commits at the beginning and the one inbetween?

**Comment by maierl** [comment]
not sure if they were already included somewhere else, but the result looks fine and the individual changes of the merge commits, too.

**Comment by maierl** [comment]
should we change all logger calls to the new `LOGGER` and make it static?

**Comment by dietzc** [comment]
> not sure if they were already included somewhere else, but the result looks fine and the individual changes of the merge commits, too.

It's just that they are unnecessary and somehow pollute the history. Let's try to avoid them in the future. Anyway, I will merge! Thanks!

**Pull request merged**
