### PR TITLE
close image reader after reading ilastik output when appending / repl…

### PR DESCRIPTION
**Pull request by maierl**
…acing columns to the table

fixes https://tech.knime.org/forum/knime-image-processing/ilastik-error-when-executing-ilastik-headless-node

### CODE REVIEW

**Comment by dietzc** [comment]
hi @maierl thanks for your PR. Are you sure that this is the right place to close the opener? Because the opener may be reused by the next row. So, I think it might make sense to add a method to the factory class which is called after _all_ rows have been processed?

Thanks again,

Christian

**Comment by maierl** [comment]
You are probably right, I don't like closing the reader within the file loop so much either.
It does work though ;)
No but seriously: changing the SingleCellFactory of KNIME itself was a bit out of my reach. If it doesn't interfere with anything in the KNIME architecture, that could be a better solution.

**Comment by maierl** [comment]
anyways, I'm not sure why the file locking is different on Windows compared to Linux... probably that difference is not really intended by Scifio.

**Comment by dietzc** [comment]
> No but seriously: changing the SingleCellFactory of KNIME itself was a bit out of my reach. If it doesn't interfere with anything in the KNIME architecture, that could be a better solution.

I will take care about this tomorrow or so. You can actually simply inherit from the factory and extend it.

**Comment by ctrueden** [comment]
> anyways, I'm not sure why the file locking is different on Windows compared to Linux

Windows file locking is much more draconian than on Linux. There is always additional pain to make things work properly on Windows, since you cannot e.g. delete a file while it is open on Windows.

**Comment by maierl** [comment]
> You can actually simply inherit from the factory and extend it.

well, just thought the same :) thanks for taking care!

**Comment by dietzc** [comment]
@maierl 
https://github.com/knime-ip/knip-ilastik/tree/close-imgopener

can you check this?

**Comment by maierl** [comment]
I like your version better ;), will test this later today.

**Comment by maierl** [comment]
:+1:

**Pull request closed without merging**
